services:

  # Django WSGI for Gunicorn
  django_app:
    build:
      context: ./attendly
    volumes:
      - ./attendly:/attendly
    ports:
      - "8000:8000"
    command: gunicorn attendly.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  # Database postgres
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=attendly_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./attendly:/attendly
    depends_on:
      - django_app

volumes:
  database:
