services:

  # Database postgres
  db:
    container_name: postgres
    image: postgres
    volumes:
      - database:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=attendly_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql
    ports:  # for development without docker
      - 5431:5432

  # Django webapp
  app:
    container_name: webapp
    build: ./attendly
    volumes:
      - ./attendly:/attendly
    ports:
      - 8000:8000
    image: app:attendly
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  database:

