# Generated by Django 4.2.6 on 2023-10-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("device", "0001_initial"),
        ("profiles", "0001_initial"),
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="device.rfiddevice"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="college.room"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="device.rfidtag"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="college.workshop",
            ),
        ),
    ]
