# Generated by Django 4.2.6 on 2023-10-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("college", "0003_room_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
