# Generated by Django 4.2.6 on 2023-10-09 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("college", "0006_subject_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="user",
        ),
    ]
