# Generated by Django 4.2.6 on 2023-10-22 05:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("college", "0008_attendance_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceInsight",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("profiles.userprofile",),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
