# Generated by Django 4.2.6 on 2023-10-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("college", "0006_subject_semester"),
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfiddevice",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="college.subject",
            ),
        ),
    ]
