# Generated by Django 4.2.6 on 2023-10-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("device", "0003_alter_rfidtag_tag_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidtag",
            name="registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rfidtag",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.userprofile",
            ),
        ),
    ]
