# Generated by Django 4.2.6 on 2023-10-21 11:30

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0004_rfidtag_registered_alter_rfidtag_profile"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="rfidtag",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="rfidtag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rfidtag",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Used for soft delete"),
        ),
        migrations.AddField(
            model_name="rfidtag",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
